// Code generated by protoc-gen-go. DO NOT EDIT.
// source: darknet/darknet.proto

package darknet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DarknetFlow struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	InBytes              uint64   `protobuf:"varint,2,opt,name=in_bytes,json=inBytes,proto3" json:"in_bytes,omitempty"`
	InPkts               uint64   `protobuf:"varint,3,opt,name=in_pkts,json=inPkts,proto3" json:"in_pkts,omitempty"`
	InputPort            uint32   `protobuf:"varint,4,opt,name=input_port,json=inputPort,proto3" json:"input_port,omitempty"`
	Ipv4DstAddr          uint32   `protobuf:"varint,5,opt,name=ipv4_dst_addr,json=ipv4DstAddr,proto3" json:"ipv4_dst_addr,omitempty"`
	Ipv4SrcAddr          uint32   `protobuf:"varint,6,opt,name=ipv4_src_addr,json=ipv4SrcAddr,proto3" json:"ipv4_src_addr,omitempty"`
	L4DstPort            uint32   `protobuf:"varint,7,opt,name=l4_dst_port,json=l4DstPort,proto3" json:"l4_dst_port,omitempty"`
	L4SrcPort            uint32   `protobuf:"varint,8,opt,name=l4_src_port,json=l4SrcPort,proto3" json:"l4_src_port,omitempty"`
	OutputPort           uint32   `protobuf:"varint,9,opt,name=output_port,json=outputPort,proto3" json:"output_port,omitempty"`
	Protocol             uint32   `protobuf:"varint,10,opt,name=protocol,proto3" json:"protocol,omitempty"`
	TcpFlags             uint32   `protobuf:"varint,11,opt,name=tcp_flags,json=tcpFlags,proto3" json:"tcp_flags,omitempty"`
	VlanIn               uint32   `protobuf:"varint,12,opt,name=vlan_in,json=vlanIn,proto3" json:"vlan_in,omitempty"`
	VlanOut              uint32   `protobuf:"varint,13,opt,name=vlan_out,json=vlanOut,proto3" json:"vlan_out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DarknetFlow) Reset()         { *m = DarknetFlow{} }
func (m *DarknetFlow) String() string { return proto.CompactTextString(m) }
func (*DarknetFlow) ProtoMessage()    {}
func (*DarknetFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c79ed737219ef73, []int{0}
}

func (m *DarknetFlow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DarknetFlow.Unmarshal(m, b)
}
func (m *DarknetFlow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DarknetFlow.Marshal(b, m, deterministic)
}
func (m *DarknetFlow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DarknetFlow.Merge(m, src)
}
func (m *DarknetFlow) XXX_Size() int {
	return xxx_messageInfo_DarknetFlow.Size(m)
}
func (m *DarknetFlow) XXX_DiscardUnknown() {
	xxx_messageInfo_DarknetFlow.DiscardUnknown(m)
}

var xxx_messageInfo_DarknetFlow proto.InternalMessageInfo

func (m *DarknetFlow) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DarknetFlow) GetInBytes() uint64 {
	if m != nil {
		return m.InBytes
	}
	return 0
}

func (m *DarknetFlow) GetInPkts() uint64 {
	if m != nil {
		return m.InPkts
	}
	return 0
}

func (m *DarknetFlow) GetInputPort() uint32 {
	if m != nil {
		return m.InputPort
	}
	return 0
}

func (m *DarknetFlow) GetIpv4DstAddr() uint32 {
	if m != nil {
		return m.Ipv4DstAddr
	}
	return 0
}

func (m *DarknetFlow) GetIpv4SrcAddr() uint32 {
	if m != nil {
		return m.Ipv4SrcAddr
	}
	return 0
}

func (m *DarknetFlow) GetL4DstPort() uint32 {
	if m != nil {
		return m.L4DstPort
	}
	return 0
}

func (m *DarknetFlow) GetL4SrcPort() uint32 {
	if m != nil {
		return m.L4SrcPort
	}
	return 0
}

func (m *DarknetFlow) GetOutputPort() uint32 {
	if m != nil {
		return m.OutputPort
	}
	return 0
}

func (m *DarknetFlow) GetProtocol() uint32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}

func (m *DarknetFlow) GetTcpFlags() uint32 {
	if m != nil {
		return m.TcpFlags
	}
	return 0
}

func (m *DarknetFlow) GetVlanIn() uint32 {
	if m != nil {
		return m.VlanIn
	}
	return 0
}

func (m *DarknetFlow) GetVlanOut() uint32 {
	if m != nil {
		return m.VlanOut
	}
	return 0
}

type DarknetFlows struct {
	Flow                 []*DarknetFlow `protobuf:"bytes,1,rep,name=flow,proto3" json:"flow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DarknetFlows) Reset()         { *m = DarknetFlows{} }
func (m *DarknetFlows) String() string { return proto.CompactTextString(m) }
func (*DarknetFlows) ProtoMessage()    {}
func (*DarknetFlows) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c79ed737219ef73, []int{1}
}

func (m *DarknetFlows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DarknetFlows.Unmarshal(m, b)
}
func (m *DarknetFlows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DarknetFlows.Marshal(b, m, deterministic)
}
func (m *DarknetFlows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DarknetFlows.Merge(m, src)
}
func (m *DarknetFlows) XXX_Size() int {
	return xxx_messageInfo_DarknetFlows.Size(m)
}
func (m *DarknetFlows) XXX_DiscardUnknown() {
	xxx_messageInfo_DarknetFlows.DiscardUnknown(m)
}

var xxx_messageInfo_DarknetFlows proto.InternalMessageInfo

func (m *DarknetFlows) GetFlow() []*DarknetFlow {
	if m != nil {
		return m.Flow
	}
	return nil
}

func init() {
	proto.RegisterType((*DarknetFlow)(nil), "darknet.DarknetFlow")
	proto.RegisterType((*DarknetFlows)(nil), "darknet.DarknetFlows")
}

func init() { proto.RegisterFile("darknet/darknet.proto", fileDescriptor_7c79ed737219ef73) }

var fileDescriptor_7c79ed737219ef73 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcb, 0x6a, 0xeb, 0x30,
	0x10, 0x86, 0xf1, 0x71, 0x8e, 0x1d, 0x8f, 0x93, 0x8d, 0x68, 0xa9, 0x7a, 0x37, 0x59, 0x79, 0x95,
	0x42, 0xdb, 0x45, 0xb7, 0x2d, 0x21, 0xd0, 0x55, 0x83, 0xf3, 0x00, 0xc6, 0xb1, 0x93, 0x22, 0xe2,
	0x48, 0x42, 0x1a, 0x27, 0xf4, 0x3d, 0xfa, 0xc0, 0x45, 0xa3, 0xdc, 0x56, 0xf6, 0x3f, 0xdf, 0xc7,
	0x8c, 0x98, 0x81, 0xcb, 0xa6, 0x32, 0x6b, 0xb9, 0xc4, 0xa7, 0xfd, 0x77, 0xac, 0x8d, 0x42, 0xc5,
	0xe2, 0x7d, 0x1c, 0xfd, 0x86, 0x90, 0x4e, 0xfc, 0xff, 0xb4, 0x55, 0x3b, 0x76, 0x07, 0x09, 0x8a,
	0xcd, 0xd2, 0x62, 0xb5, 0xd1, 0x3c, 0xc8, 0x82, 0x3c, 0x2c, 0x4e, 0x05, 0x76, 0x0d, 0x7d, 0x21,
	0xcb, 0xc5, 0x0f, 0x2e, 0x2d, 0xff, 0x97, 0x05, 0x79, 0xaf, 0x88, 0x85, 0xfc, 0x70, 0x91, 0x5d,
	0x41, 0x2c, 0x64, 0xa9, 0xd7, 0x68, 0x79, 0x48, 0x24, 0x12, 0x72, 0xb6, 0x46, 0xcb, 0xee, 0x01,
	0x84, 0xd4, 0x1d, 0x96, 0x5a, 0x19, 0xe4, 0xbd, 0x2c, 0xc8, 0x87, 0x45, 0x42, 0x95, 0x99, 0x32,
	0xc8, 0x46, 0x30, 0x14, 0x7a, 0xfb, 0x5a, 0x36, 0x16, 0xcb, 0xaa, 0x69, 0x0c, 0xff, 0x4f, 0x46,
	0xea, 0x8a, 0x13, 0x8b, 0xef, 0x4d, 0x63, 0x8e, 0x8e, 0x35, 0xb5, 0x77, 0xa2, 0x93, 0x33, 0x37,
	0x35, 0x39, 0x0f, 0x90, 0xb6, 0xbe, 0x0b, 0xcd, 0x89, 0xfd, 0x9c, 0xd6, 0xf5, 0xa0, 0x39, 0x9e,
	0xbb, 0x0e, 0xc4, 0xfb, 0x07, 0x3e, 0x37, 0x35, 0xf1, 0x47, 0x48, 0x55, 0x87, 0xc7, 0x77, 0x26,
	0xc4, 0xc1, 0x97, 0x48, 0xb8, 0x81, 0x3e, 0xed, 0xae, 0x56, 0x2d, 0x07, 0xa2, 0xc7, 0xcc, 0x6e,
	0x21, 0xc1, 0x5a, 0x97, 0xab, 0xb6, 0xfa, 0xb6, 0x3c, 0xf5, 0x10, 0x6b, 0x3d, 0x75, 0xd9, 0x6d,
	0x66, 0xdb, 0x56, 0xb2, 0x14, 0x92, 0x0f, 0x08, 0x45, 0x2e, 0x7e, 0x4a, 0xb7, 0x4d, 0x02, 0xaa,
	0x43, 0x3e, 0x24, 0x42, 0xe2, 0x57, 0x87, 0xa3, 0x37, 0x18, 0x9c, 0x5d, 0xc5, 0xb2, 0x1c, 0x7a,
	0xab, 0x56, 0xed, 0x78, 0x90, 0x85, 0x79, 0xfa, 0x7c, 0x31, 0x3e, 0x5c, 0xf3, 0x4c, 0x2a, 0xc8,
	0x58, 0x44, 0xf4, 0xa8, 0x97, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0x26, 0x47, 0xb8, 0xf9,
	0x01, 0x00, 0x00,
}
